### ISSUE TITLE
Add a subcommand to print complete recipe for an app

### ISSUE THREAD

**Issue by PrasadG193** [kbrew-dev/kbrew#120]
The command could be like - `kbrew recipe kafka` which should print complete recipe details for better understanding or debugging

**Comment by sahil-lakhwani** [comment]
I think we can use the `info` command by having a sub-command or a flag (--verbose). Thoughts?

**Comment by JOSHUAJEBARAJ** [comment]
I would llike to work on this issue, Let me know how we can take forward this issue

**Comment by sahil-lakhwani** [comment]
hey @JOSHUAJEBARAJ :wave: 
You might want to look at the implementation of the [info command](https://github.com/kbrew-dev/kbrew/blob/19a388f0ce233142753e0f4e58b12d59e3e2d83e/cmd/cli/main.go#L158) - it does a similar job of printing a summary of a recipe. This issue is for printing the complete recipe.

While we work to build a contributing guide, you can use the Makefile to build the binary from the source (make build) after you make any changes
Let us know if you need any help!

**Comment by JOSHUAJEBARAJ** [comment]
Hey Sahil 👋 
I had look at the `info` Command Can You explain what is the additional information you want to print 

For example the `kbrew info argo-cd` gives the below output 

```yaml
repository:
  name: argo
  url: https://argoproj.github.io/argo-helm
  type: helm
version: 3.6.2
``` 

THe registry config looks like something like this  for the argo-cd 
```yaml 
apiVersion: v1
kind: kbrew
app:
  repository:
    name: argo
    url: https://argoproj.github.io/argo-helm
    type: helm
  namespace: "argocd"
  sha256:
  version: 3.6.2

```
What are the additional detail it should Print ?
