### ISSUE TITLE
Main install named steps confusing to user

### ISSUE THREAD

**Issue by vishal-biyani** [kbrew-dev/kbrew#25]
The main `steps` can be confusing with the pre & post-install's step. Should we have a different name there?

```
  pre_install:
  - steps:
    - # Do something
  - steps:
  post_install:
  - steps:
```
