### ISSUE TITLE
Add support for passing args to the kbrew app

### ISSUE THREAD

**Issue by PrasadG193** [kbrew-dev/kbrew#63]
Update recipe struct to default values for args for an app. 

For an helm app, args could be the helm values for the chart
```
  args: 
    # key: value/ref. For helm app key would be the helm value key
    replicas: 3
    persistent.storageclass: {{ .params.storageClass }} | user input --option
```

For raw/manifest app, the key would be the manifest path (jsonpath). We need to check if we can update the raw app manifest fields at runtime using jsonpath syntax
```
  app:
  - args:
      # for raw/manifest app, the key would be the manifest path (jsonpath)
      .spec.containers[*].env[?(@.name=="MYSQL_ROOT_PASSWORD")].value: {{ .mysqlPassword }}
      .spec.storageClass: {{ lookup }}
    name: custom-app
```
