### ISSUE TITLE
Create namespace if does not exist for raw apps

### ISSUE THREAD

**Issue by PrasadG193** [kbrew-dev/kbrew#80]
For raw app types, if passed namespace as arg or recipe field, the installation fails if the namespace doesn't exist. In such case, we should create the namespace if it doesn't exist.

sample recipe:
```
apiVersion: v1
kind: kbrew
app:
  repository:
    name: local-storage
    url: https://raw.githubusercontent.com/kubernetes-sigs/sig-storage-local-static-provisioner/master/examples/manual-pv.yaml
    type: raw
  namespace: <namespace-that-doesn't-exist>

```
